配列型のjsonのレスポンスチェックに対応させる
aktsk/atgen pull request #53
Opened 2023-11-13 03:39 UTC by seipan

配列型のjsonのレスポンスチェックに対応させる

2023-11-13 03:47 UTC, seipan commented
こんな感じで生成されます。
```go
func TestNestedDataInRegisters(t *testing.T) {
	r := handlers.GetRouter()
	ts := httptest.NewServer(r)
	defer ts.Close()

	atgenRegister := map[string]interface{}{}

	client := new(http.Client)

	{

		atgenReqParams := map[string]interface{}(nil)

		atgenReqBody, _ := json.Marshal(
			atgenReqParams,
		)

		req, _ := http.NewRequest(
			"GET",
			ts.URL+"/v1/people",
			bytes.NewReader(atgenReqBody),
		)

		atgenReqHeaders := map[string]string(nil)

		for h, v := range atgenReqHeaders {
			req.Header.Set(h, v)
		}

		res, _ := client.Do(req)

		if res.StatusCode != 200 {
			t.Log(res.Body)
			t.Errorf("Expected status code should be %d, but actually %d", 200, res.StatusCode)
		}

		atgenResHeaders := map[string]string{}

		for h, v := range atgenResHeaders {
			actually := res.Header.Get(h)
			if actually != v {
				t.Errorf("%v header should be %v, but actually %v", h, v, actually)
			}
		}

		params := make(map[string]interface{})
		flag := false
		arrayparams := make([]map[string]interface{}, 0)
		buf := new(bytes.Buffer)
		buf.ReadFrom(res.Body)
		resBody := buf.String()
		if resBody != "" {
			err := json.Unmarshal([]byte(resBody), &params)
			if err != nil {
				arrayerr := json.Unmarshal([]byte(resBody), &arrayparams)
				if err != nil {
					t.Fatal(err, arrayerr)
				}
				flag = true
			}
		}

		if !flag {

			atgenResParams := map[string]interface{}{}

			checkCompare(t, params, atgenResParams)
		} else {
			atgenResParamsArray := []map[string]interface{}{}

			checkCompareArray(t, arrayparams, atgenResParamsArray)
		}

		atgenRegister["people"] = params
	}
	{

		atgenReqParams := map[string]interface{}(nil)

		atgenReqBody, _ := json.Marshal(
			atgenReqParams,
		)

		req, _ := http.NewRequest(
			"GET",
			ts.URL+"/v1/people/1",
			bytes.NewReader(atgenReqBody),
		)

		atgenReqHeaders := map[string]string(nil)

		for h, v := range atgenReqHeaders {
			req.Header.Set(h, v)
		}

		res, _ := client.Do(req)

		if res.StatusCode != 200 {
			t.Log(res.Body)
			t.Errorf("Expected status code should be %d, but actually %d", 200, res.StatusCode)
		}

		atgenResHeaders := map[string]string{}

		for h, v := range atgenResHeaders {
			actually := res.Header.Get(h)
			if actually != v {
				t.Errorf("%v header should be %v, but actually %v", h, v, actually)
			}
		}

		params := make(map[string]interface{})
		flag := false
		arrayparams := make([]map[string]interface{}, 0)
		buf := new(bytes.Buffer)
		buf.ReadFrom(res.Body)
		resBody := buf.String()
		if resBody != "" {
			err := json.Unmarshal([]byte(resBody), &params)
			if err != nil {
				arrayerr := json.Unmarshal([]byte(resBody), &arrayparams)
				if err != nil {
					t.Fatal(err, arrayerr)
				}
				flag = true
			}
		}

		if !flag {

			atgenResParams := map[string]interface{}{}

			checkCompare(t, params, atgenResParams)
		} else {
			atgenResParamsArray := []map[string]interface{}{map[string]interface{}{"firstname": "John", "id": "1", "lastname": "Doe"}, map[string]interface{}{"firstname": "Jane", "id": "2", "lastname": "Doe"}}

			checkCompareArray(t, arrayparams, atgenResParamsArray)
		}

		atgenRegister[""] = params
	}

}
```

2023-11-13 04:55 UTC, takanakahiko approved these changes
ありがとうございます！
何点か気になった部分を書いておきましたので確認お願いします 🙏

2023-11-13 04:55 UTC, takanakahiko commented on example/template/template_test.go
> +		flag := false
flag という名前だと何を判定する flag なのかわからないので、 もう少し詳細な名前が良さそうです

2023-11-13 04:55 UTC, takanakahiko commented on example/template/main_test.yaml
最後の改行を忘れないようしてください

2023-11-13 04:55 UTC, takanakahiko commented on example/template/template_test.go
> +				if err != nil {
こうですかね？

```suggestion
				if arrayerr != nil {
```

2023-11-13 04:55 UTC, takanakahiko commented on example/template/util_test.go
> +func checkCompareArray(t *testing.T, actual, expected interface{}) {
中身が `func checkCompare(t *testing.T, actual, expected interface{})` と全く同じであるように思うのですが、別の関数にした理由があれば教えて欲しいです！

2023-11-13 04:55 UTC, takanakahiko requested changes
間違えました 😭

2023-11-13 06:24 UTC, seipan commented on example/template/util_test.go
> +func checkCompareArray(t *testing.T, actual, expected interface{}) {
ミスです！修正します！

2023-11-13 07:28 UTC, takanakahiko requested changes
五月雨で申し訳ないですが、追加のコメントをしたので確認お願いします！

2023-11-13 07:28 UTC, takanakahiko commented on example/template/template_test.go
> +				isMapArray = true
わかりやすい命名ですね！良いと思います

2023-11-13 07:28 UTC, takanakahiko commented on example/template/main_test.yaml
> +- name: TestNestedDataInRegisters
Test の名前はコピーしたものではなく適切なものに変更しましょうか

2023-11-13 07:28 UTC, takanakahiko commented on example/template/main_test.yaml
> +
最後に ⛔ のマークが出ているのが気になりますね。
最後の行を改行で終わらせないと出るものなんですが、改行で終わってるしなんでだろう？
改行コードの問題だったりするんですかね？
これがない状態の方が混乱が少ないと思うので、調査して修正していただけると嬉しいです。

2023-11-13 07:28 UTC, takanakahiko commented on example/template/template_test.go
> +					t.Fatal(err, arrayerr)
err も arrayerr も出力しているのはわかりやすくていいですね！さすがっす

2023-11-13 07:28 UTC, takanakahiko commented on lib/types.go
> +	ParamsArray []map[string]interface{}
Params と ParamsArray の意味合いはほぼ同じなので、隣にあった方が「同じ役割のパラメータなんだな」と分かって親切かなと思いました。

```suggestion
	Params      map[string]interface{}
	ParamsArray []map[string]interface{}
	Headers     map[string]string
```

2023-11-13 08:47 UTC, seipan commented on example/template/main_test.yaml
> +
これで出来てそうですかね？

2023-11-13 09:12 UTC, seipan commented on lib/types.go
> +	ParamsArray []map[string]interface{}
修正しました！

2023-11-15 01:56 UTC, takanakahiko approved these changes
当初より配列の判定部分など、かなり見通しがかなり良くなりましたね！
![LGTM](https://i.lgtm.fun/2mkf.png)

2023-11-15 01:56 UTC, merged